// Copyright TheMonHub 2026.
// Distributed under the Boost Software License, Version 1.0.
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef KURO_BOOT_H
#define KURO_BOOT_H

#include "kuro.h"

#include <stdint.h>

typedef struct {
    void *km_map; // Provide your own EFI_MEMORY_DESCRIPTOR structure
    uint64_t km_map_size;
    uint64_t km_desc_size;
    uint32_t km_desc_version;
    uintptr_t km_higher_half_base;
    uint64_t km_execmem_size;
    uint64_t km_progstack_size;
    uint64_t km_bootinfo_size;
    uintptr_t km_bootinfo_base;
} KuroMemoryMap;

typedef struct {
    void *km_module_base;
    uint64_t km_module_size;
} KuroModule;

typedef struct {
  uint32_t RedMask;
  uint32_t GreenMask;
  uint32_t BlueMask;
  uint32_t ReservedMask;
} KURO_EFI_PIXEL_BITMASK;

typedef struct {
  void *kf_base;
  uint64_t kf_size;
  uint32_t kf_width;
  uint32_t kf_height;
  uint32_t kf_pixels_per_scanline;
  uint32_t kf_pixel_format;
  KURO_EFI_PIXEL_BITMASK kf_pixel_info;
} KuroFramebuffer;

typedef struct {
  uint32_t ks_flags;
  uintptr_t ks_address;
  uint64_t ks_size;
  uint64_t ks_align;
} KuroSegmentInfo;

typedef struct {
  uintptr_t ke_entry_point;
  uint64_t ke_segment_count;
  KuroSegmentInfo* ke_segments;
  uint64_t ke_stack_start;
  uint64_t ke_stack_size;
} KuroExecutableInfo;

typedef struct {
    KuroIdentifier kb_identifier;
    char *kb_boot_id;
    char *kb_cmdline;
    void *kb_system_table; // Provide your own EFI_SYSTEM_TABLE structure
    KuroMemoryMap *kb_memory_map;
    KuroModule *kb_module;
    KuroFramebuffer *kb_framebuffer;
    KuroExecutableInfo *kb_executable_info;
} KuroBootInfo;

#endif //KURO_BOOT_H
